---
title: "Market Analysis"
author: "Curran Bhatia, Anupriya Tripathi, Krti Tallam, Nick Favale, Aaron Gilbert"
date: "4/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(stringr)
library(readr)
library(dplyr)
```

### Read in Data
```{r, echo=TRUE}

set.seed(222)

readInStocks = function(n, date1 = "2015") {
  # Gives n random stocks from the S & P 500
  # 
  # Args:
  #   n: Number of stocks to be read
  # 
  # Returns:
  #   List of dataframes with each stock's close value for each day
  
  snp = read_csv("Stocks.csv")
  
  #nums = sample(1:500, n)
  #arr100 = snp$Symbol[nums]
  #sec100 = snp$Sector[nums]
  
   dateN = date1 %>% as.character() %>% substring(1,4) %>% as.numeric()
   print(dateN)
  
  #array = arr100
  
  
  nums = c()
  
  
  stocks_2005 = list()
  
  i = 1
  while (i <= n) {
  #for (i in 1:n) {

    num = sample(1:500, 1)
    
     while (num %in% nums) {
       num = sample(1:500, 1)
       
       if (length(nums) > n) {
         return(-1)
       }
     }
    
    arr = snp$Symbol[num]
    
    # print("num is")
    # print(num)
    # print("i is ")
    # print(i)
    
    dir = c("../Stocks/", as.character(arr), ".us.txt")
    
    dir2 = str_c(dir, collapse = "")
    #print(dir2)
    if(!file.exists(dir2)) {
      next
    }
    stock = read.table(dir2, sep=",", header=TRUE)
    stock[3] <- NULL
    stock[3] <- NULL
    stock[4] <- NULL
    stock[4] <- NULL
    stock[2] <- NULL
  
    stock$name <- arr
    
    

    
    beg = stock$Date[1] %>% as.character() %>% substring(1,4) %>% as.numeric()
    end = stock$Date[length(stock$Date)] %>% as.character() %>% substring(1,4) %>% as.numeric()
    
    
    if (beg > dateN || end < dateN) {
      
      i = i-1
      
      #print("Enters here")
      
      #nums = sample(1:500, n)
      #arr100 = snp$Symbol[nums]
      #sec100 = snp$Sector[nums]
    }
    else {
      stocks_2005[[i]] <- stock
    }
    
    
    i = i+1
  }

  return(stocks_2005)

}


#readInStocks(50) -> vals


```


### Read Difference
```{r, echo=TRUE}

closeDiffPct = function(n, firstDate, secondDate, stocks_2005) {
  # Gives difference in close values from firstDate to secondDate
  # 
  # Args:
  #   n: Number of stocks to be read that are in stocks_2005
  #   firstDate: The first Date
  #   seconDate: The second Date
  #   stocks_2005: List of stock dataframes
  # 
  # Returns:
  #   A dataframe with the difference in percentage of close values, 
  #   with the stock name next to it
  
  
  rets = numeric(n)
  names = c()
  
  
  
  for (i in 1:n) {
     stock_df = stocks_2005[[i]]
     stock_df$Date = as.character(stock_df$Date)
     firstN = which(stock_df$Date == firstDate)
     secondN = which(stock_df$Date == secondDate)
     #print(firstN)
     #print(secondN)
     
     if ((is.integer(firstN) && length(firstN) == 0) | 
         (is.integer(secondN) && length(secondN) == 0)) {
       
       names = c("", names)
       next
     }
  
     stock_close_03 <- stock_df[firstN,]$Close 
     stock_close_04 <- stock_df[secondN,]$Close
     s_2005 <- (stock_close_04-stock_close_03)/stock_close_03
     
     #print(s_2005)
     rets[i] = s_2005
     names = c(stock_df$name[1], names)
  }
  
   return2005 = data.frame(rets, names)
   return2005
   
   return(return2005)
    
}




```


### Run Code
```{r}

#set.seed(679)

#Run code
# stocks = readInStocks(250)
# readValues = closeDiffPct(250, "2005-03-01", "2005-06-01", stocks)
# readValues
# hist(readValues$rets)
# mean(readValues$rets)
# var(readValues$rets)

```

Prior distribution: $$g({\theta},{\sigma^2}) = Normal() * InverseGamma() $$
Likelihood function: $$L({\mu},{\sigma^2};x_1,...,x_n) = (2\pi{\sigma^2})^{-n/2}  exp({-1/{2\sigma^2}} \sum\limits_{j=1}^n (x_j - \mu)^2)$$
Posterior distribution: $$g(\theta,\sigma^2 | x_i) = L({\mu},{\sigma^2};x_1,...,x_n) * g({\theta},{\sigma^2})$$



###Graph Data
```{r}
# hist(readValues$rets)
# mean(readValues$rets)
# var(readValues$rets)
```
###Prior
```{r}

# g_prior = function(x = seq(-1,1,.01), theta = 0, var1 = 1, alpha = 3, beta = 1) {
#   #return(dnorm(x, theta, var1)*dgamma(x, alpha, beta))
#   return(dnorm(x)*1)
# }

```

```{r}
# x <- seq(-1,1,.01)
# hist(g_prior(x, theta, var1, alpha, beta))
# gp = g_prior(x, theta, var1, alpha, beta)
# plot(x,gp)
```



###Making First Likelihood Function
```{r}
L = function(theta, x, n, sigma2 = 2){
  first = (2*pi*sigma2)^(-n/2)
  second = exp((-1/(2*sigma2))*sum((x - theta)^2))
  return(first*second)
}

```


### Finding Posterior and Running Code
```{r}
set.seed(679)


gprior = function (theta, mu = 0, sigma = 2) {
  return (dnorm(theta, mu, sigma))
}



n = 80

# Get return differences
stocks = readInStocks(n)
readValues = closeDiffPct(n, "2005-03-01", "2005-06-01", stocks)
rets = readValues$rets


# posterior distribution
theta = seq(-10, 8, length.out = n)
gp = gprior(theta)
Li = L(theta, rets, n)
post = Li*gp

plot(theta, post)


c = L(theta, rets, n) * gprior(rnorm(n))
C = mean(c)

postC = (post/C)

plot(theta, postC)


```


### Markov Chain
```{r}

#markov = function (n, dates ) {

n= 80
dates = c("2008-03-04", "2009-03-03", "2010-03-03")



  set.seed(679)


  # Get return differences
  theta = seq(-8, 8, length.out = n)
  
  
  finalPost = gprior(theta)
  
  list1 = list()
  
  for (i in 1:(length(dates)-1)) {
    
    #i = 1
    stocks = readInStocks(n)
    readValues = closeDiffPct(n, dates[i], dates[i+1], stocks)
    rets = readValues$rets
    
    Li = L(theta, rets, n)
    
    c = L(theta, rets, n) * gprior(rnorm(n))
    C = mean(c)
  
  
    finalPost = finalPost*(Li/C)
    
    list1[[i]] = rets
  
  }
  
  plot(theta, finalPost)
  
  # The theta value for the max finalPost
  maxInd = which.max(finalPost)
  theta[maxInd]
  paste("The value of theta for the max value in our final posterior distribution is : ",   theta[maxInd])

#}


```

```{r}

#markov = function (n, dates ) {

n= 120
dates = c("2005-03-01", "2006-03-01", "2007-03-01", "2008-03-04")



  set.seed(100)


  # Get return differences
  theta = seq(-8, 8, length.out = n)
  
  
  finalPost = gprior(theta)
  
  list1 = list()
  
  for (i in 1:(length(dates)-1)) {
    
    #i = 1
    stocks = readInStocks(n)
    readValues = closeDiffPct(n, dates[i], dates[i+1], stocks)
    rets = readValues$rets
    
    Li = L(theta, rets, n)
    
    c = L(theta, rets, n) * gprior(rnorm(n))
    C = mean(c)
  
  
    finalPost = finalPost*(Li/C)
    
    list1[[i]] = rets
  
  }
  
  plot(theta, finalPost)
  
  # The theta value for the max finalPost
  maxInd = which.max(finalPost)
  theta[maxInd]
  paste("The value of theta for the max value in our final posterior distribution is : ",   theta[maxInd])

#}


```


```{r}

dates = c("2005-03-01", "2005-04-01", "2005-05-02", "2005-06-01", "2005-07-01")
markov(n = 80, dates = dates)

dates = c("2005-03-01", "2006-03-01", "2007-03-01", "2008-03-04")
markov(n = 80, dates = dates)

dates = c("2008-03-04", "2009-03-03", "2010-03-03")
markov(n= 80, dates = dates)


```

